
```yaml
version: '3'

services:
  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=unleash
      - DATABASE_USERNAME=unleash_user
      - DATABASE_PASSWORD=unleash_pass
      - DATABASE_SSL=false
      - INIT_FRONTEND_API_TOKENS=default:development.unleash-insecure-api-token
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: unleash_pass
      POSTGRES_DB: unleash
