version: '3.7'

services:
  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://unleash_user:password@db/unleash"
      DATABASE_SSL: "false"
      LOG_LEVEL: "info"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
